sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: oioi2
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: lhp-javaweb
  wechat:
    appid: wx0b98f9123282a3ca
    secret: f23d299ce8b7a0a3105d8be932319a1c